# Generated by Django 5.2.7 on 2025-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, choices=[('Jakarta', 'Jakarta'), ('Surabaya', 'Surabaya'), ('Bandung', 'Bandung'), ('Medan', 'Medan'), ('Semarang', 'Semarang'), ('Makassar', 'Makassar'), ('Palembang', 'Palembang'), ('Tangerang', 'Tangerang'), ('Depok', 'Depok'), ('Bekasi', 'Bekasi'), ('Bogor', 'Bogor'), ('Batam', 'Batam'), ('Pekanbaru', 'Pekanbaru'), ('Bandar Lampung', 'Bandar Lampung'), ('Padang', 'Padang'), ('Malang', 'Malang'), ('Denpasar', 'Denpasar'), ('Samarinda', 'Samarinda'), ('Banjarmasin', 'Banjarmasin'), ('Pontianak', 'Pontianak'), ('Balikpapan', 'Balikpapan'), ('Jambi', 'Jambi'), ('Yogyakarta', 'Yogyakarta'), ('Manado', 'Manado'), ('Cirebon', 'Cirebon')], max_length=128),
        ),
    ]
