version: "3.9"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5173
  #   depends_on:
  #     - backend

  db:
    image: postgres:16.6-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=event_manager
      - POSTGRES_PASSWORD=event_manager_password
      - POSTGRES_DB=event_manager

volumes:
  postgres_data:
